/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/woman/ninja2.glb 
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ninja2({ isMobile }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/woman/ninja2.glb')
  const { actions , names } = useAnimations(animations, group)
  console.log(actions);
  console.log(names);
  useEffect(() => {
    actions[names[1]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[1]].fadeOut(0.5);
    };
  }, []);
  return (
    <group ref={group}  dispose={null}>
      <group name="Scene">
        <group name="Armature" 
        rotation={[Math.PI / 2, 0, 0]} 
        scale={isMobile ? 0.008 : 0.01}
        position={isMobile ? [-0.1, -1.6, 0] : [-2, -3.05,1]}>
          <primitive object={nodes.mixamorigHips}  
          />
          <skinnedMesh name="Ch24" geometry={nodes.Ch24.geometry} material={materials.Ch24_Body} skeleton={nodes.Ch24.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/woman/ninja2.glb')
