/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/plane/plane.gltf 
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Plane({ isMobile }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/plane/plane.gltf')
  const { actions , names } = useAnimations(animations, group)
  const index = 0;
  useEffect(() => {
    actions[names[index]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[index]].fadeOut(0.5);
    };
  }, []);
  return (
    <group ref={group}  dispose={null}>
      <group name="Scene" position={isMobile? [0,0.8,0] :[2,0.5,0]} rotation={[0,0.5,0]} scale={isMobile ? 0.3 :0.25}>
        <group name="Point001" position={[1.335, -1.064, -1.57]} rotation={[0, 0.04, -0.001]} scale={0.607} />
        <group name="Point002" position={[-1.418, -1.032, -1.572]} rotation={[0, 0.04, -0.001]} scale={0.662} />
        <group name="Point003" position={[1.283, 0.113, -8.217]} rotation={[0.002, 0.04, -0.042]} />
        <group name="Point004" position={[-0.87, 0.291, -8.198]} rotation={[0.002, 0.04, -0.042]} />
        <group name="Area" position={[-2.906, -0.486, -1.632]} rotation={[-1.582, 0.016, -1.266]} scale={[2.47, 1, 1]} />
        <group name="Area001" position={[2.937, -0.535, -1.821]} rotation={[1.585, -0.012, -1.24]} scale={[-2.464, -0.997, -0.997]} />
        <group name="Point005" position={[1.149, 0.253, -5.541]} rotation={[1.571, -0.001, -0.025]} scale={3.739} />
        <group name="Point006" position={[-1.075, 0.256, -5.542]} rotation={[1.571, -0.001, -0.025]} scale={4.081} />
        <group name="Empty" position={[-1.075, 0.256, -5.542]} />
        <group name="Empty001" position={[1.149, 0.253, -5.541]} />
        <mesh name="Baked_Animations_Intergalactic_Spaceships_Version_2" geometry={nodes.Baked_Animations_Intergalactic_Spaceships_Version_2.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.002']} position={[-1.025, 0.18, -5.284]} scale={[1, 1, 1.253]} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.002']} position={[1.033, 0.175, -5.274]} scale={[1, 1, 1.253]} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.003']} position={[-1.025, 0.18, -7.729]} rotation={[0, 0, -2.513]} scale={0.47} />
        <mesh name="Torus004" geometry={nodes.Torus004.geometry} material={materials['Material.003']} position={[-1.025, 0.18, -2.765]} />
        <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials['Material.003']} position={[1.033, 0.175, -7.719]} rotation={[0, 0, -2.513]} scale={0.47} />
        <mesh name="Torus000" geometry={nodes.Torus000.geometry} material={materials['Material.003']} position={[1.033, 0.175, -8.696]} rotation={[0, 0, -1.885]} scale={0.106} />
        <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['Material.003']} position={[-1.025, 0.18, -6.751]} rotation={[0, 0, -1.885]} scale={0.838} />
        <mesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials['Material.003']} position={[-1.025, 0.18, -5.773]} rotation={[0, 0, -0.628]} scale={1.06} />
        <mesh name="Torus005" geometry={nodes.Torus005.geometry} material={materials['Material.003']} position={[1.033, 0.175, -5.763]} rotation={[0, 0, -0.628]} scale={1.06} />
        <mesh name="Torus006" geometry={nodes.Torus006.geometry} material={materials['Material.003']} position={[1.033, 0.175, -6.741]} rotation={[0, 0, -1.885]} scale={0.838} />
      </group>
    </group>
  )
}

useGLTF.preload('/plane/plane.gltf')
